version: '3'
services:
# Based on https://github.com/DataDog/docker-compose-example
  dog_container:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=5bdb06c9289aeb5ea13280f68bca994c
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_TAGS=env:${ENVIRONMENT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
  game_api:
    image: arnimegg/hgop:${GIT_COMMIT}
    ports:
    - '3000:3000'
    depends_on:
    - game_database_container
    environment:
      PORT: 3000
      POSTGRES_HOST: 'game_database_container'
      POSTGRES_DB: 'game_database'
      POSTGRES_USER: 'my_user'
      POSTGRES_PASSWORD: 'my_password'
  game_client:
    image: arnimegg/hgop:game-ui-${GIT_COMMIT}
    ports:
      - '4000:4000'
    depends_on:
      - game_api
    environment:
      PORT: 4000
      API_PORT: 3000
      API_URL: ${API_URL}
  game_database_container:
    image: postgres
    environment:
      POSTGRES_DB: 'game_database'
      POSTGRES_USER: 'my_user'
      POSTGRES_PASSWORD: 'my_password'